language: python
python:
- '3.5'
addons:
  apt:
    packages:
    - rsync
install: pip install csscompressor
script: ./generate-page.py
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
before_deploy:
- openssl aes-256-cbc -K $encrypted_4d02832aa0f5_key -iv $encrypted_4d02832aa0f5_iv -in scripts/.deploy_key.enc -out ~/.ssh/id_rsa -d
- chmod 400 ~/.ssh/id_rsa
