name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ruby ruby-dev make gcc
        sudo apt-get install translate-toolkit rsync
        sudo gem install bundler
        bundle install

    - name: Build website
      run: |
        scripts/build.sh

    - name: Deploy to server
      if: github.event_name == 'push'
      run: |
        mkdir -p $HOME/.ssh/
        chmod 700 $HOME/.ssh/
        echo -n "${{ secrets.SSH_MATEY }}" > $HOME/.ssh/id_rsa
        chmod 600 $HOME/.ssh/id_rsa
        scripts/deploy.sh
